[project]
name = "graph_weather"
version = "1.0.43"
description = "Graph-based AI Weather models"
authors = ["Jacob Bieker <jacob@bieker.tech>"]
channels = ["pyg", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64"]

[tasks]
tinstall = "python -m pip install torch-geometric-temporal"

[dependencies]
python = "3.11.*"
torchvision = ">=0.16.1,<0.17"
pytorch-cluster = ">=1.6.3,<1.7"
pytorch-scatter = ">=2.1.2,<2.2"
pytorch-cuda = "12.1.*"
xarray = ">=2024.2.0,<2024.3"
pytorch-spline-conv = ">=1.2.2,<1.3"
pytorch = ">=2.1"
pandas = ">=2.2.1,<2.3"
h3-py = ">=3.7.6,<3.8"
numcodecs = ">=0.12.1,<0.13"
scipy = ">=1.12.0,<1.13"
zarr = ">=2.17.0,<2.18"
pyg = ">=2.5.0,<2.6"
tqdm = ">=4.66.2,<4.67"
pytorch-sparse = ">=0.6.18,<0.7"
lightning = ">=2.2.0.post0,<2.2.1"
einops = ">=0.7.0,<0.8"
fsspec = ">=2024.2.0,<2024.3"
datasets = ">=2.18.0,<2.19"
pip = ">=24.0,<25"


[pypi-dependencies]
pytest = "*"  # This means any version (this `*` is custom in pixi)
pre-commit = "*"
pysolar = "*"
